# Port to run server
port: 7980

doLogging: true
logLevel: "INFO"

dbConfig:
  hostName: "localhost"
  port: 5432
  user: "savely"
  dbName: "db"
  dbPassword: ""

dbPoolSettings:
  # Size of the pool (Integer)
  size: 10
  # An amount of time for which an unused resource is kept open. (Integer)
  timeout: 5
