name:                server
version:             0.1.0.0
github:              "krendelhoff/server"
license:             BSD3
author:              "Savely Krendelhoff"
maintainer:          "dklaptove@edu.hse.ru"
copyright:           "2021 Savely Krendelhoff"

extra-source-files:
- README.org

data-files:
- migrations/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Advanced server app.

dependencies:
- base
- universum
- exceptions
- mtl
- text
- text-show
- bytestring
- aeson
- template-haskell
- deriving-aeson
- lens
- filepath
- raw-strings-qq
- file-embed
- time
- warp
- wai
- wai-extra
- hasql
- hasql-th
- hasql-pool
- hasql-dynamic-statements
- hasql-transaction
- hasql-migration
- uuid
- http-types
- http-api-data
- path-pieces
- cryptonite
- time
- word8
- dhall
- fmt
- tasty
- tasty-hspec
- tasty-hedgehog

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src

executables:
  server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
    - tasty
    - tasty-hspec
    - tasty-hedgehog
