name:                server-lib
version:             0.1.0.0
github:              "krendelhoff/server"
license:             BSD3
author:              "Savely Krendelhoff"
maintainer:          "dklaptove@edu.hse.ru"
copyright:           "2021 Savely Krendelhoff"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Advanced server app library.

dependencies:
- base
- universum
- exceptions
- mtl
- text
- text-show
- bytestring
- aeson
- template-haskell
- deriving-aeson
- lens
- filepath
- raw-strings-qq
- file-embed
- time
- data-has
- warp
- wai
- wai-extra
- hasql
- hasql-th
- hasql-pool
- hasql-dynamic-statements
- hasql-transaction
- hasql-migration
- uuid
- http-types
- http-api-data
- path-pieces
- cryptonite
- time
- word8
- dhall
- fmt

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
